#!/bin/bash

set -e

echo "AZURE_RESOURCES_NAME_PREFIX: '${AZURE_RESOURCES_NAME_PREFIX}'"
echo "AZURE_RESOURCES_NAME_ID: '${AZURE_RESOURCES_NAME_ID}'"
echo "AZURE_DEPLOYMENT_LOCATION: '${AZURE_DEPLOYMENT_LOCATION}'"
echo "DRY_RUN: '${DRY_RUN}'"

set +e
