#!/bin/bash

set -e

echo "GIT_REPOSITORY_NAME: '${GIT_REPOSITORY_NAME}'"
echo "AZURE_RESOURCES_NAME_PREFIX: '${AZURE_RESOURCES_NAME_PREFIX}'"
echo "AZURE_RESOURCES_NAME_ID: '${AZURE_RESOURCES_NAME_ID}'"
echo "DRY_RUN: '${DRY_RUN}'"

set +e
